DROP TABLE `analyses_photos_chantier`;--> statement-breakpoint
DROP TABLE `articles_artisan`;--> statement-breakpoint
DROP TABLE `articles_fournisseurs`;--> statement-breakpoint
DROP TABLE `artisans`;--> statement-breakpoint
DROP TABLE `assurances_vehicules`;--> statement-breakpoint
DROP TABLE `avis_clients`;--> statement-breakpoint
DROP TABLE `badges`;--> statement-breakpoint
DROP TABLE `badges_techniciens`;--> statement-breakpoint
DROP TABLE `bibliotheque_articles`;--> statement-breakpoint
DROP TABLE `chantiers`;--> statement-breakpoint
DROP TABLE `classement_techniciens`;--> statement-breakpoint
DROP TABLE `client_portal_access`;--> statement-breakpoint
DROP TABLE `client_portal_sessions`;--> statement-breakpoint
DROP TABLE `clients`;--> statement-breakpoint
DROP TABLE `commandes_fournisseurs`;--> statement-breakpoint
DROP TABLE `config_alertes_previsions`;--> statement-breakpoint
DROP TABLE `config_relances_auto`;--> statement-breakpoint
DROP TABLE `configurations_comptables`;--> statement-breakpoint
DROP TABLE `conges`;--> statement-breakpoint
DROP TABLE `contrats_maintenance`;--> statement-breakpoint
DROP TABLE `conversations`;--> statement-breakpoint
DROP TABLE `demandes_avis`;--> statement-breakpoint
DROP TABLE `devis`;--> statement-breakpoint
DROP TABLE `devis_genere_ia`;--> statement-breakpoint
DROP TABLE `devis_lignes`;--> statement-breakpoint
DROP TABLE `devis_options`;--> statement-breakpoint
DROP TABLE `devis_options_lignes`;--> statement-breakpoint
DROP TABLE `disponibilites_techniciens`;--> statement-breakpoint
DROP TABLE `documents_chantier`;--> statement-breakpoint
DROP TABLE `ecritures_comptables`;--> statement-breakpoint
DROP TABLE `entretiens_vehicules`;--> statement-breakpoint
DROP TABLE `executions_rapports`;--> statement-breakpoint
DROP TABLE `exports_comptables`;--> statement-breakpoint
DROP TABLE `factures`;--> statement-breakpoint
DROP TABLE `factures_lignes`;--> statement-breakpoint
DROP TABLE `factures_recurrentes`;--> statement-breakpoint
DROP TABLE `fournisseurs`;--> statement-breakpoint
DROP TABLE `historique_alertes_previsions`;--> statement-breakpoint
DROP TABLE `historique_ca`;--> statement-breakpoint
DROP TABLE `historique_deplacements`;--> statement-breakpoint
DROP TABLE `historique_kilometrage`;--> statement-breakpoint
DROP TABLE `historique_notifications_push`;--> statement-breakpoint
DROP TABLE `interventions`;--> statement-breakpoint
DROP TABLE `interventions_chantier`;--> statement-breakpoint
DROP TABLE `interventions_mobile`;--> statement-breakpoint
DROP TABLE `lignes_commandes_fournisseurs`;--> statement-breakpoint
DROP TABLE `messages`;--> statement-breakpoint
DROP TABLE `modeles_devis`;--> statement-breakpoint
DROP TABLE `modeles_devis_lignes`;--> statement-breakpoint
DROP TABLE `modeles_email`;--> statement-breakpoint
DROP TABLE `mouvements_stock`;--> statement-breakpoint
DROP TABLE `notifications`;--> statement-breakpoint
DROP TABLE `objectifs_techniciens`;--> statement-breakpoint
DROP TABLE `paiements_stripe`;--> statement-breakpoint
DROP TABLE `parametres_artisan`;--> statement-breakpoint
DROP TABLE `phases_chantier`;--> statement-breakpoint
DROP TABLE `photos_analyse`;--> statement-breakpoint
DROP TABLE `photos_interventions`;--> statement-breakpoint
DROP TABLE `plan_comptable`;--> statement-breakpoint
DROP TABLE `positions_techniciens`;--> statement-breakpoint
DROP TABLE `preferences_couleurs_calendrier`;--> statement-breakpoint
DROP TABLE `preferences_notifications`;--> statement-breakpoint
DROP TABLE `previsions_ca`;--> statement-breakpoint
DROP TABLE `push_subscriptions`;--> statement-breakpoint
DROP TABLE `rapports_personnalises`;--> statement-breakpoint
DROP TABLE `relances_devis`;--> statement-breakpoint
DROP TABLE `resultats_analyse_ia`;--> statement-breakpoint
DROP TABLE `signatures_devis`;--> statement-breakpoint
DROP TABLE `sms_verifications`;--> statement-breakpoint
DROP TABLE `soldes_conges`;--> statement-breakpoint
DROP TABLE `stocks`;--> statement-breakpoint
DROP TABLE `suggestions_articles_ia`;--> statement-breakpoint
DROP TABLE `techniciens`;--> statement-breakpoint
DROP TABLE `vehicules`;--> statement-breakpoint
ALTER TABLE `users` DROP INDEX `users_email_unique`;--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `openId` varchar(64) NOT NULL;--> statement-breakpoint
ALTER TABLE `users` DROP COLUMN `password`;