// drizzle/schema.pg.ts — OPE-184 / P0.3 : schéma PostgreSQL cible (PG-first).
//
// Conversion mécanique de drizzle/schema.ts (MySQL) vers pg-core, en appliquant
// docs/architecture/ope-184-mapping-types-mysql-pg.md. Construit par batchs
// (P0.3 = plateforme + cœur facturation ; P0.4/P0.5 pour le reste).
//
// L'ancien drizzle/schema.ts (mysql) reste la source du stack LEGACY jusqu'au
// repoint de getDb() sur node-postgres (P0.7). Ce fichier n'est encore importé
// nulle part : il est validé en isolation via `tsconfig.src.json`.
//
// Règles appliquées :
//  - int autoincrement PK -> serial (GENERATED BY DEFAULT : autorise la copie
//    des ids existants en P0.8, séquences recalées ensuite).
//  - datetime/timestamp -> timestamp ; onUpdateNow() -> $onUpdate (app-level).
//  - decimal -> numeric ; mediumtext -> text ; mysqlEnum -> pgEnum (déclaré 1x).
//  - noms de colonnes identiques (quotés) pour minimiser la friction de copie.
import {
  pgTable,
  pgEnum,
  serial,
  integer,
  varchar,
  text,
  timestamp,
  date,
  boolean,
  numeric,
  bigint,
} from "drizzle-orm/pg-core";

// ── Enums ──────────────────────────────────────────────────────────────────
export const userRoleEnum = pgEnum("user_role", ["admin", "artisan", "secretaire", "technicien"]);
export const artisanSpecialiteEnum = pgEnum("artisan_specialite", ["plomberie", "electricite", "chauffage", "multi-services"]);
export const formeJuridiqueEnum = pgEnum("forme_juridique", ["EI", "micro", "EURL", "SARL", "SAS", "SASU", "SA", "autre"]);
export const clientTypeEnum = pgEnum("client_type", ["particulier", "professionnel"]);

// ── USERS ──────────────────────────────────────────────────────────────────
export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  openId: varchar("openId", { length: 64 }).unique(),
  name: text("name"),
  prenom: varchar("prenom", { length: 255 }),
  email: varchar("email", { length: 320 }).unique(),
  password: varchar("password", { length: 255 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: userRoleEnum("role").default("artisan").notNull(),
  artisanId: integer("artisanId"),
  actif: boolean("actif").default(true).notNull(),
  resetToken: varchar("resetToken", { length: 64 }),
  resetTokenExpiry: timestamp("resetTokenExpiry"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().$onUpdate(() => new Date()).notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});
export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

// ── PERMISSIONS UTILISATEUR ────────────────────────────────────────────────
export const permissionsUtilisateur = pgTable("permissions_utilisateur", {
  id: serial("id").primaryKey(),
  userId: integer("userId").notNull(),
  permission: varchar("permission", { length: 50 }).notNull(),
  autorise: boolean("autorise").default(true).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type PermissionUtilisateur = typeof permissionsUtilisateur.$inferSelect;
export type InsertPermissionUtilisateur = typeof permissionsUtilisateur.$inferInsert;

// ── ARTISANS ───────────────────────────────────────────────────────────────
export const artisans = pgTable("artisans", {
  id: serial("id").primaryKey(),
  userId: integer("userId").notNull().unique(),
  siret: varchar("siret", { length: 14 }),
  nomEntreprise: varchar("nomEntreprise", { length: 255 }),
  adresse: text("adresse"),
  codePostal: varchar("codePostal", { length: 10 }),
  ville: varchar("ville", { length: 100 }),
  telephone: varchar("telephone", { length: 20 }),
  email: varchar("email", { length: 320 }),
  specialite: artisanSpecialiteEnum("specialite").default("plomberie"),
  tauxTVA: numeric("tauxTVA", { precision: 5, scale: 2 }).default("20.00"),
  numeroTVA: varchar("numeroTVA", { length: 20 }),
  iban: varchar("iban", { length: 34 }),
  codeAPE: varchar("codeAPE", { length: 10 }),
  formeJuridique: formeJuridiqueEnum("formeJuridique"),
  capitalSocial: numeric("capitalSocial", { precision: 12, scale: 2 }),
  villeRCS: varchar("villeRCS", { length: 100 }),
  numeroRM: varchar("numeroRM", { length: 50 }),
  logo: text("logo"),
  slug: varchar("slug", { length: 255 }).unique(),
  icalToken: varchar("icalToken", { length: 64 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().$onUpdate(() => new Date()).notNull(),
});
export type Artisan = typeof artisans.$inferSelect;
export type InsertArtisan = typeof artisans.$inferInsert;

// ── CLIENTS ────────────────────────────────────────────────────────────────
export const clients = pgTable("clients", {
  id: serial("id").primaryKey(),
  artisanId: integer("artisanId").notNull(),
  nom: varchar("nom", { length: 255 }).notNull(),
  prenom: varchar("prenom", { length: 255 }),
  email: varchar("email", { length: 320 }),
  telephone: varchar("telephone", { length: 20 }),
  adresse: text("adresse"),
  codePostal: varchar("codePostal", { length: 10 }),
  ville: varchar("ville", { length: 100 }),
  adresseFacturation: text("adresseFacturation"),
  codePostalFacturation: varchar("codePostalFacturation", { length: 10 }),
  villeFacturation: varchar("villeFacturation", { length: 100 }),
  type: clientTypeEnum("type").default("particulier"),
  raisonSociale: varchar("raisonSociale", { length: 255 }),
  siret: varchar("siret", { length: 14 }),
  numeroTVA: varchar("numeroTVA", { length: 20 }),
  etiquettes: varchar("etiquettes", { length: 500 }),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().$onUpdate(() => new Date()).notNull(),
});
export type Client = typeof clients.$inferSelect;
export type InsertClient = typeof clients.$inferInsert;

// ── SESSIONS ───────────────────────────────────────────────────────────────
export const sessions = pgTable("sessions", {
  id: varchar("id", { length: 128 }).primaryKey(),
  userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }),
  expiresAt: bigint("expiresAt", { mode: "number" }).notNull(),
});
export type Session = typeof sessions.$inferSelect;
export type InsertSession = typeof sessions.$inferInsert;

// ── AUDIT LOG ──────────────────────────────────────────────────────────────
export const auditLog = pgTable("audit_log", {
  id: serial("id").primaryKey(),
  artisanId: integer("artisanId").notNull(),
  userId: integer("userId").notNull(),
  entityType: varchar("entityType", { length: 50 }).notNull(),
  entityId: integer("entityId").notNull(),
  action: varchar("action", { length: 50 }).notNull(),
  details: text("details"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type AuditLog = typeof auditLog.$inferSelect;
export type InsertAuditLog = typeof auditLog.$inferInsert;

// ── Enums cœur facturation (P0.3b) ───────────────────────────────────────────
export const devisStatutEnum = pgEnum("devis_statut", ["brouillon", "envoye", "accepte", "refuse", "expire"]);
export const ligneTypeEnum = pgEnum("ligne_type", ["produit", "section", "note"]); // partagé devis_lignes / factures_lignes
export const factureStatutEnum = pgEnum("facture_statut", ["brouillon", "validee", "envoyee", "payee", "en_retard", "annulee"]);
export const factureTypeDocumentEnum = pgEnum("facture_type_document", ["facture", "avoir"]);
export const delaiPaiementTypeEnum = pgEnum("delai_paiement_type", ["net", "fin_de_mois"]);
export const signatureStatutEnum = pgEnum("signature_statut", ["en_attente", "accepte", "refuse"]);

// ── BIBLIOTHEQUE ARTICLES ────────────────────────────────────────────────────
export const bibliothequeArticles = pgTable("bibliotheque_articles", {
  id: serial("id").primaryKey(),
  metier: varchar("metier", { length: 50 }).notNull(),
  categorie: varchar("categorie", { length: 50 }).notNull(),
  sous_categorie: varchar("sous_categorie", { length: 100 }).notNull(),
  nom: varchar("nom", { length: 255 }).notNull(),
  description: text("description"),
  prix_base: numeric("prix_base", { precision: 10, scale: 2 }).notNull(),
  unite: varchar("unite", { length: 50 }).notNull(),
  tauxTVA: numeric("tauxTVA", { precision: 5, scale: 2 }).default("20.00"),
  prixRevient: numeric("prixRevient", { precision: 10, scale: 2 }),
  duree_moyenne_minutes: integer("duree_moyenne_minutes"),
  visible: boolean("visible").default(true),
  created_at: timestamp("created_at").defaultNow(),
  updated_at: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()),
});
export type BibliothequeArticle = typeof bibliothequeArticles.$inferSelect;
export type InsertBibliothequeArticle = typeof bibliothequeArticles.$inferInsert;

// ── ARTICLES ARTISAN ─────────────────────────────────────────────────────────
export const articlesArtisan = pgTable("articles_artisan", {
  id: serial("id").primaryKey(),
  artisanId: integer("artisanId").notNull(),
  reference: varchar("reference", { length: 50 }).notNull(),
  designation: varchar("designation", { length: 500 }).notNull(),
  description: text("description"),
  unite: varchar("unite", { length: 20 }).default("unité"),
  prixUnitaireHT: numeric("prixUnitaireHT", { precision: 10, scale: 2 }).notNull(),
  tauxTVA: numeric("tauxTVA", { precision: 5, scale: 2 }).default("20.00"),
  categorie: varchar("categorie", { length: 100 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().$onUpdate(() => new Date()).notNull(),
});
export type ArticleArtisan = typeof articlesArtisan.$inferSelect;
export type InsertArticleArtisan = typeof articlesArtisan.$inferInsert;

// ── ARTICLES FOURNISSEURS ────────────────────────────────────────────────────
export const articlesFournisseurs = pgTable("articles_fournisseurs", {
  id: serial("id").primaryKey(),
  articleId: integer("articleId").notNull(),
  fournisseurId: integer("fournisseurId").notNull(),
  referenceExterne: varchar("referenceExterne", { length: 100 }),
  prixAchat: numeric("prixAchat", { precision: 10, scale: 2 }),
  delaiLivraison: integer("delaiLivraison"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type ArticleFournisseur = typeof articlesFournisseurs.$inferSelect;
export type InsertArticleFournisseur = typeof articlesFournisseurs.$inferInsert;

// ── DEVIS ──────────────────────────────────────────────────────────────────
export const devis = pgTable("devis", {
  id: serial("id").primaryKey(),
  artisanId: integer("artisanId").notNull(),
  clientId: integer("clientId").notNull(),
  numero: varchar("numero", { length: 50 }).notNull(),
  dateDevis: timestamp("dateDevis").defaultNow().notNull(),
  dateValidite: timestamp("dateValidite"),
  dateVue: timestamp("dateVue"),
  statut: devisStatutEnum("statut").default("brouillon"),
  objet: text("objet"),
  referenceClient: varchar("referenceClient", { length: 100 }),
  conditionsPaiement: text("conditionsPaiement"),
  notes: text("notes"),
  totalHT: numeric("totalHT", { precision: 10, scale: 2 }).default("0.00"),
  totalTVA: numeric("totalTVA", { precision: 10, scale: 2 }).default("0.00"),
  totalTTC: numeric("totalTTC", { precision: 10, scale: 2 }).default("0.00"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().$onUpdate(() => new Date()).notNull(),
});
export type Devis = typeof devis.$inferSelect;
export type InsertDevis = typeof devis.$inferInsert;

// ── DEVIS LIGNES ─────────────────────────────────────────────────────────────
export const devisLignes = pgTable("devis_lignes", {
  id: serial("id").primaryKey(),
  devisId: integer("devisId").notNull(),
  ordre: integer("ordre").default(0),
  reference: varchar("reference", { length: 50 }),
  designation: varchar("designation", { length: 500 }).notNull(),
  description: text("description"),
  quantite: numeric("quantite", { precision: 10, scale: 2 }).default("1.00"),
  unite: varchar("unite", { length: 20 }).default("unité"),
  prixUnitaireHT: numeric("prixUnitaireHT", { precision: 10, scale: 2 }).notNull(),
  tauxTVA: numeric("tauxTVA", { precision: 5, scale: 2 }).default("20.00"),
  montantHT: numeric("montantHT", { precision: 10, scale: 2 }).default("0.00"),
  montantTVA: numeric("montantTVA", { precision: 10, scale: 2 }).default("0.00"),
  montantTTC: numeric("montantTTC", { precision: 10, scale: 2 }).default("0.00"),
  type: ligneTypeEnum("type").default("produit"),
});
export type DevisLigne = typeof devisLignes.$inferSelect;
export type InsertDevisLigne = typeof devisLignes.$inferInsert;

// ── FACTURES ───────────────────────────────────────────────────────────────
export const factures = pgTable("factures", {
  id: serial("id").primaryKey(),
  artisanId: integer("artisanId").notNull(),
  clientId: integer("clientId").notNull(),
  devisId: integer("devisId"),
  numero: varchar("numero", { length: 50 }).notNull(),
  dateFacture: timestamp("dateFacture").defaultNow().notNull(),
  dateEcheance: timestamp("dateEcheance"),
  statut: factureStatutEnum("statut").default("brouillon"),
  typeDocument: factureTypeDocumentEnum("typeDocument").default("facture"),
  factureOrigineId: integer("factureOrigineId"),
  objet: text("objet"),
  referenceClient: varchar("referenceClient", { length: 100 }),
  siretDestinataire: varchar("siretDestinataire", { length: 14 }),
  conditionsPaiement: text("conditionsPaiement"),
  notes: text("notes"),
  totalHT: numeric("totalHT", { precision: 10, scale: 2 }).default("0.00"),
  totalTVA: numeric("totalTVA", { precision: 10, scale: 2 }).default("0.00"),
  totalTTC: numeric("totalTTC", { precision: 10, scale: 2 }).default("0.00"),
  montantPaye: numeric("montantPaye", { precision: 10, scale: 2 }).default("0.00"),
  datePaiement: timestamp("datePaiement"),
  modePaiement: varchar("modePaiement", { length: 50 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().$onUpdate(() => new Date()).notNull(),
});
export type Facture = typeof factures.$inferSelect;
export type InsertFacture = typeof factures.$inferInsert;

// ── FACTURES LIGNES ──────────────────────────────────────────────────────────
export const facturesLignes = pgTable("factures_lignes", {
  id: serial("id").primaryKey(),
  factureId: integer("factureId").notNull(),
  ordre: integer("ordre").default(0),
  reference: varchar("reference", { length: 50 }),
  designation: varchar("designation", { length: 500 }).notNull(),
  description: text("description"),
  quantite: numeric("quantite", { precision: 10, scale: 2 }).default("1.00"),
  unite: varchar("unite", { length: 20 }).default("unité"),
  prixUnitaireHT: numeric("prixUnitaireHT", { precision: 10, scale: 2 }).notNull(),
  tauxTVA: numeric("tauxTVA", { precision: 5, scale: 2 }).default("20.00"),
  montantHT: numeric("montantHT", { precision: 10, scale: 2 }).default("0.00"),
  montantTVA: numeric("montantTVA", { precision: 10, scale: 2 }).default("0.00"),
  montantTTC: numeric("montantTTC", { precision: 10, scale: 2 }).default("0.00"),
  type: ligneTypeEnum("type").default("produit"),
});
export type FactureLigne = typeof facturesLignes.$inferSelect;
export type InsertFactureLigne = typeof facturesLignes.$inferInsert;

// ── SIGNATURES DEVIS ─────────────────────────────────────────────────────────
export const signaturesDevis = pgTable("signatures_devis", {
  id: serial("id").primaryKey(),
  devisId: integer("devisId").notNull().unique(),
  token: varchar("token", { length: 64 }).notNull().unique(),
  statut: signatureStatutEnum("statut").default("en_attente"),
  signatureData: text("signatureData"),
  signataireName: varchar("signataireName", { length: 255 }),
  signataireEmail: varchar("signataireEmail", { length: 320 }),
  ipAddress: varchar("ipAddress", { length: 45 }),
  userAgent: text("userAgent"),
  motifRefus: text("motifRefus"),
  signedAt: timestamp("signedAt"),
  expiresAt: timestamp("expiresAt").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type SignatureDevis = typeof signaturesDevis.$inferSelect;
export type InsertSignatureDevis = typeof signaturesDevis.$inferInsert;

// ── PARAMETRES ARTISAN ───────────────────────────────────────────────────────
export const parametresArtisan = pgTable("parametres_artisan", {
  id: serial("id").primaryKey(),
  artisanId: integer("artisanId").notNull().unique(),
  prefixeDevis: varchar("prefixeDevis", { length: 10 }).default("DEV"),
  prefixeFacture: varchar("prefixeFacture", { length: 10 }).default("FAC"),
  prefixeAvoir: varchar("prefixeAvoir", { length: 10 }).default("AV"),
  compteurDevis: integer("compteurDevis").default(1),
  compteurFacture: integer("compteurFacture").default(1),
  compteurAvoir: integer("compteurAvoir").default(1),
  mentionsLegales: text("mentionsLegales"),
  conditionsGenerales: text("conditionsGenerales"),
  notificationsEmail: boolean("notificationsEmail").default(true),
  rappelDevisJours: integer("rappelDevisJours").default(7),
  rappelFactureJours: integer("rappelFactureJours").default(30),
  objectifCA: numeric("objectifCA", { precision: 10, scale: 2 }).default("0"),
  objectifDevis: integer("objectifDevis").default(0),
  objectifClients: integer("objectifClients").default(0),
  vitrineActive: boolean("vitrineActive").default(false),
  vitrineDescription: text("vitrineDescription"),
  vitrineZone: varchar("vitrineZone", { length: 500 }),
  vitrineServices: text("vitrineServices"),
  vitrineExperience: integer("vitrineExperience"),
  couleurPrincipale: varchar("couleurPrincipale", { length: 20 }).default("#4F46E5"),
  couleurSecondaire: varchar("couleurSecondaire", { length: 20 }).default("#6366F1"),
  conditionsPaiementDefaut: text("conditionsPaiementDefaut"),
  delaiPaiementJours: integer("delaiPaiementJours"),
  delaiPaiementType: delaiPaiementTypeEnum("delaiPaiementType").default("net"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().$onUpdate(() => new Date()).notNull(),
});
export type ParametresArtisan = typeof parametresArtisan.$inferSelect;
export type InsertParametresArtisan = typeof parametresArtisan.$inferInsert;

// ── DEVIS OPTIONS ────────────────────────────────────────────────────────────
export const devisOptions = pgTable("devis_options", {
  id: serial("id").primaryKey(),
  devisId: integer("devisId").notNull(),
  nom: varchar("nom", { length: 100 }).notNull(),
  description: text("description"),
  ordre: integer("ordre").default(1),
  totalHT: numeric("totalHT", { precision: 10, scale: 2 }).default("0.00"),
  totalTVA: numeric("totalTVA", { precision: 10, scale: 2 }).default("0.00"),
  totalTTC: numeric("totalTTC", { precision: 10, scale: 2 }).default("0.00"),
  recommandee: boolean("recommandee").default(false),
  selectionnee: boolean("selectionnee").default(false),
  dateSelection: timestamp("dateSelection"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().$onUpdate(() => new Date()).notNull(),
});
export type DevisOption = typeof devisOptions.$inferSelect;
export type InsertDevisOption = typeof devisOptions.$inferInsert;

// ── DEVIS OPTIONS LIGNES ─────────────────────────────────────────────────────
export const devisOptionsLignes = pgTable("devis_options_lignes", {
  id: serial("id").primaryKey(),
  optionId: integer("optionId").notNull(),
  articleId: integer("articleId"),
  designation: varchar("designation", { length: 255 }).notNull(),
  description: text("description"),
  quantite: numeric("quantite", { precision: 10, scale: 2 }).default("1.00"),
  unite: varchar("unite", { length: 20 }).default("unité"),
  prixUnitaireHT: numeric("prixUnitaireHT", { precision: 10, scale: 2 }).default("0.00"),
  tauxTVA: numeric("tauxTVA", { precision: 5, scale: 2 }).default("20.00"),
  remise: numeric("remise", { precision: 5, scale: 2 }).default("0.00"),
  montantHT: numeric("montantHT", { precision: 10, scale: 2 }).default("0.00"),
  montantTVA: numeric("montantTVA", { precision: 10, scale: 2 }).default("0.00"),
  montantTTC: numeric("montantTTC", { precision: 10, scale: 2 }).default("0.00"),
  ordre: integer("ordre").default(1),
});
export type DevisOptionLigne = typeof devisOptionsLignes.$inferSelect;
export type InsertDevisOptionLigne = typeof devisOptionsLignes.$inferInsert;

// ── MODELES DEVIS ────────────────────────────────────────────────────────────
export const modelesDevis = pgTable("modeles_devis", {
  id: serial("id").primaryKey(),
  artisanId: integer("artisanId").notNull(),
  nom: varchar("nom", { length: 255 }).notNull(),
  description: text("description"),
  notes: text("notes"),
  isDefault: boolean("isDefault").default(false),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().$onUpdate(() => new Date()).notNull(),
});
export type ModeleDevis = typeof modelesDevis.$inferSelect;
export type InsertModeleDevis = typeof modelesDevis.$inferInsert;

// ── MODELES DEVIS LIGNES ─────────────────────────────────────────────────────
export const modelesDevisLignes = pgTable("modeles_devis_lignes", {
  id: serial("id").primaryKey(),
  modeleId: integer("modeleId").notNull(),
  articleId: integer("articleId"),
  designation: varchar("designation", { length: 255 }).notNull(),
  description: text("description"),
  quantite: numeric("quantite", { precision: 10, scale: 2 }).default("1.00"),
  unite: varchar("unite", { length: 20 }).default("unité"),
  prixUnitaireHT: numeric("prixUnitaireHT", { precision: 10, scale: 2 }).default("0.00"),
  tauxTVA: numeric("tauxTVA", { precision: 5, scale: 2 }).default("20.00"),
  remise: numeric("remise", { precision: 5, scale: 2 }).default("0.00"),
  ordre: integer("ordre").default(1),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type ModeleDevisLigne = typeof modelesDevisLignes.$inferSelect;
export type InsertModeleDevisLigne = typeof modelesDevisLignes.$inferInsert;

// ════════════════════════════════════════════════════════════════════════════
// BATCH 2a (P0.4) — TERRAIN : interventions, techniciens, véhicules
// ════════════════════════════════════════════════════════════════════════════
export const interventionStatutEnum = pgEnum("intervention_statut", ["planifiee", "en_cours", "terminee", "annulee"]);
export const technicienStatutEnum = pgEnum("technicien_statut", ["actif", "inactif", "conge"]);
export const vehiculeCarburantEnum = pgEnum("vehicule_carburant", ["essence", "diesel", "electrique", "hybride", "gpl"]);
export const vehiculeStatutEnum = pgEnum("vehicule_statut", ["actif", "en_maintenance", "hors_service", "vendu"]);
export const entretienTypeEnum = pgEnum("entretien_type", ["vidange", "pneus", "freins", "controle_technique", "revision", "reparation", "autre"]);
export const assuranceTypeEnum = pgEnum("assurance_type", ["tiers", "tiers_plus", "tous_risques"]);
export const classementPeriodeEnum = pgEnum("classement_periode", ["semaine", "mois", "trimestre", "annee"]);

// ── INTERVENTIONS ────────────────────────────────────────────────────────────
export const interventions = pgTable("interventions", {
  id: serial("id").primaryKey(),
  artisanId: integer("artisanId").notNull(),
  clientId: integer("clientId").notNull(),
  titre: varchar("titre", { length: 255 }).notNull(),
  description: text("description"),
  dateDebut: timestamp("dateDebut").notNull(),
  dateFin: timestamp("dateFin"),
  statut: interventionStatutEnum("statut").default("planifiee"),
  adresse: text("adresse"),
  notes: text("notes"),
  devisId: integer("devisId"),
  factureId: integer("factureId"),
  technicienId: integer("technicienId"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().$onUpdate(() => new Date()).notNull(),
});
export type Intervention = typeof interventions.$inferSelect;
export type InsertIntervention = typeof interventions.$inferInsert;

// ── INTERVENTIONS TECHNICIENS (équipe) ───────────────────────────────────────
export const interventionsTechniciens = pgTable("interventions_techniciens", {
  id: serial("id").primaryKey(),
  artisanId: integer("artisanId").notNull(),
  interventionId: integer("interventionId").notNull(),
  technicienId: integer("technicienId").notNull(),
  role: varchar("role", { length: 50 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type InterventionTechnicien = typeof interventionsTechniciens.$inferSelect;
export type InsertInterventionTechnicien = typeof interventionsTechniciens.$inferInsert;

// ── TECHNICIENS ──────────────────────────────────────────────────────────────
export const techniciens = pgTable("techniciens", {
  id: serial("id").primaryKey(),
  artisanId: integer("artisanId").notNull(),
  nom: varchar("nom", { length: 255 }).notNull(),
  prenom: varchar("prenom", { length: 255 }),
  email: varchar("email", { length: 320 }),
  telephone: varchar("telephone", { length: 20 }),
  specialite: varchar("specialite", { length: 100 }),
  couleur: varchar("couleur", { length: 7 }).default("#3b82f6"),
  statut: technicienStatutEnum("statut").default("actif"),
  coutHoraire: numeric("coutHoraire", { precision: 8, scale: 2 }),
  userId: integer("userId"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().notNull(),
});
export type Technicien = typeof techniciens.$inferSelect;
export type InsertTechnicien = typeof techniciens.$inferInsert;

// ── DISPONIBILITES TECHNICIENS ───────────────────────────────────────────────
export const disponibilitesTechniciens = pgTable("disponibilites_techniciens", {
  id: serial("id").primaryKey(),
  technicienId: integer("technicienId").notNull(),
  jourSemaine: integer("jourSemaine").notNull(),
  heureDebut: varchar("heureDebut", { length: 5 }).notNull(),
  heureFin: varchar("heureFin", { length: 5 }).notNull(),
  disponible: boolean("disponible").default(true),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type DisponibiliteTechnicien = typeof disponibilitesTechniciens.$inferSelect;
export type InsertDisponibiliteTechnicien = typeof disponibilitesTechniciens.$inferInsert;

// ── POSITIONS GPS TECHNICIENS ────────────────────────────────────────────────
export const positionsTechniciens = pgTable("positions_techniciens", {
  id: serial("id").primaryKey(),
  technicienId: integer("technicienId").notNull(),
  latitude: numeric("latitude", { precision: 10, scale: 8 }).notNull(),
  longitude: numeric("longitude", { precision: 11, scale: 8 }).notNull(),
  precision: integer("precision"),
  vitesse: numeric("vitesse", { precision: 5, scale: 2 }),
  cap: integer("cap"),
  batterie: integer("batterie"),
  enDeplacement: boolean("enDeplacement").default(false),
  interventionEnCoursId: integer("interventionEnCoursId"),
  timestamp: timestamp("timestamp").defaultNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type PositionTechnicien = typeof positionsTechniciens.$inferSelect;
export type InsertPositionTechnicien = typeof positionsTechniciens.$inferInsert;

// ── VEHICULES ────────────────────────────────────────────────────────────────
export const vehicules = pgTable("vehicules", {
  id: serial("id").primaryKey(),
  artisanId: integer("artisanId").notNull(),
  immatriculation: varchar("immatriculation", { length: 20 }).notNull(),
  marque: varchar("marque", { length: 100 }),
  modele: varchar("modele", { length: 100 }),
  annee: integer("annee"),
  typeCarburant: vehiculeCarburantEnum("typeCarburant").default("diesel"),
  puissanceFiscale: integer("puissanceFiscale"),
  kilometrageActuel: integer("kilometrageActuel").default(0),
  dateAchat: date("dateAchat"),
  prixAchat: numeric("prixAchat", { precision: 10, scale: 2 }),
  technicienId: integer("technicienId"),
  statut: vehiculeStatutEnum("statut").default("actif"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().$onUpdate(() => new Date()).notNull(),
});
export type Vehicule = typeof vehicules.$inferSelect;
export type InsertVehicule = typeof vehicules.$inferInsert;

// ── HISTORIQUE KILOMETRAGE ───────────────────────────────────────────────────
export const historiqueKilometrage = pgTable("historique_kilometrage", {
  id: serial("id").primaryKey(),
  vehiculeId: integer("vehiculeId").notNull(),
  technicienId: integer("technicienId"),
  kilometrage: integer("kilometrage").notNull(),
  dateReleve: date("dateReleve").notNull(),
  motif: varchar("motif", { length: 255 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type HistoriqueKilometrage = typeof historiqueKilometrage.$inferSelect;
export type InsertHistoriqueKilometrage = typeof historiqueKilometrage.$inferInsert;

// ── ENTRETIENS VEHICULES ─────────────────────────────────────────────────────
export const entretiensVehicules = pgTable("entretiens_vehicules", {
  id: serial("id").primaryKey(),
  vehiculeId: integer("vehiculeId").notNull(),
  type: entretienTypeEnum("type").notNull(),
  dateEntretien: date("dateEntretien").notNull(),
  kilometrageEntretien: integer("kilometrageEntretien"),
  cout: numeric("cout", { precision: 10, scale: 2 }),
  prestataire: varchar("prestataire", { length: 255 }),
  description: text("description"),
  prochainEntretienKm: integer("prochainEntretienKm"),
  prochainEntretienDate: date("prochainEntretienDate"),
  facture: text("facture"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type EntretienVehicule = typeof entretiensVehicules.$inferSelect;
export type InsertEntretienVehicule = typeof entretiensVehicules.$inferInsert;

// ── ASSURANCES VEHICULES ─────────────────────────────────────────────────────
export const assurancesVehicules = pgTable("assurances_vehicules", {
  id: serial("id").primaryKey(),
  vehiculeId: integer("vehiculeId").notNull(),
  compagnie: varchar("compagnie", { length: 255 }).notNull(),
  numeroContrat: varchar("numeroContrat", { length: 100 }),
  typeAssurance: assuranceTypeEnum("typeAssurance").default("tiers"),
  dateDebut: date("dateDebut").notNull(),
  dateFin: date("dateFin").notNull(),
  primeAnnuelle: numeric("primeAnnuelle", { precision: 10, scale: 2 }),
  franchise: numeric("franchise", { precision: 10, scale: 2 }),
  document: text("document"),
  alerteEnvoyee: boolean("alerteEnvoyee").default(false),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().$onUpdate(() => new Date()).notNull(),
});
export type AssuranceVehicule = typeof assurancesVehicules.$inferSelect;
export type InsertAssuranceVehicule = typeof assurancesVehicules.$inferInsert;

// ── OBJECTIFS TECHNICIENS ────────────────────────────────────────────────────
export const objectifsTechniciens = pgTable("objectifs_techniciens", {
  id: serial("id").primaryKey(),
  technicienId: integer("technicienId").notNull(),
  artisanId: integer("artisanId").notNull(),
  mois: integer("mois").notNull(),
  annee: integer("annee").notNull(),
  objectifInterventions: integer("objectifInterventions").default(0),
  objectifCA: numeric("objectifCA", { precision: 10, scale: 2 }).default("0.00"),
  objectifAvisPositifs: integer("objectifAvisPositifs").default(0),
  interventionsRealisees: integer("interventionsRealisees").default(0),
  caRealise: numeric("caRealise", { precision: 10, scale: 2 }).default("0.00"),
  avisPositifsObtenus: integer("avisPositifsObtenus").default(0),
  pointsGagnes: integer("pointsGagnes").default(0),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().$onUpdate(() => new Date()).notNull(),
});
export type ObjectifTechnicien = typeof objectifsTechniciens.$inferSelect;
export type InsertObjectifTechnicien = typeof objectifsTechniciens.$inferInsert;

// ── CLASSEMENT TECHNICIENS ───────────────────────────────────────────────────
export const classementTechniciens = pgTable("classement_techniciens", {
  id: serial("id").primaryKey(),
  technicienId: integer("technicienId").notNull(),
  artisanId: integer("artisanId").notNull(),
  periode: classementPeriodeEnum("periode").notNull(),
  dateDebut: date("dateDebut").notNull(),
  dateFin: date("dateFin").notNull(),
  rang: integer("rang").notNull(),
  pointsTotal: integer("pointsTotal").default(0),
  interventions: integer("interventions").default(0),
  ca: numeric("ca", { precision: 10, scale: 2 }).default("0.00"),
  noteMoyenne: numeric("noteMoyenne", { precision: 3, scale: 2 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type ClassementTechnicien = typeof classementTechniciens.$inferSelect;
export type InsertClassementTechnicien = typeof classementTechniciens.$inferInsert;
