// drizzle/schema.pg.ts — OPE-184 / P0.3 : schéma PostgreSQL cible (PG-first).
//
// Conversion mécanique de drizzle/schema.ts (MySQL) vers pg-core, en appliquant
// docs/architecture/ope-184-mapping-types-mysql-pg.md. Construit par batchs
// (P0.3 = plateforme + cœur facturation ; P0.4/P0.5 pour le reste).
//
// L'ancien drizzle/schema.ts (mysql) reste la source du stack LEGACY jusqu'au
// repoint de getDb() sur node-postgres (P0.7). Ce fichier n'est encore importé
// nulle part : il est validé en isolation via `tsconfig.src.json`.
//
// Règles appliquées :
//  - int autoincrement PK -> serial (GENERATED BY DEFAULT : autorise la copie
//    des ids existants en P0.8, séquences recalées ensuite).
//  - datetime/timestamp -> timestamp ; onUpdateNow() -> $onUpdate (app-level).
//  - decimal -> numeric ; mediumtext -> text ; mysqlEnum -> pgEnum (déclaré 1x).
//  - noms de colonnes identiques (quotés) pour minimiser la friction de copie.
import {
  pgTable,
  pgEnum,
  serial,
  integer,
  varchar,
  text,
  timestamp,
  boolean,
  numeric,
  bigint,
} from "drizzle-orm/pg-core";

// ── Enums ──────────────────────────────────────────────────────────────────
export const userRoleEnum = pgEnum("user_role", ["admin", "artisan", "secretaire", "technicien"]);
export const artisanSpecialiteEnum = pgEnum("artisan_specialite", ["plomberie", "electricite", "chauffage", "multi-services"]);
export const formeJuridiqueEnum = pgEnum("forme_juridique", ["EI", "micro", "EURL", "SARL", "SAS", "SASU", "SA", "autre"]);
export const clientTypeEnum = pgEnum("client_type", ["particulier", "professionnel"]);

// ── USERS ──────────────────────────────────────────────────────────────────
export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  openId: varchar("openId", { length: 64 }).unique(),
  name: text("name"),
  prenom: varchar("prenom", { length: 255 }),
  email: varchar("email", { length: 320 }).unique(),
  password: varchar("password", { length: 255 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: userRoleEnum("role").default("artisan").notNull(),
  artisanId: integer("artisanId"),
  actif: boolean("actif").default(true).notNull(),
  resetToken: varchar("resetToken", { length: 64 }),
  resetTokenExpiry: timestamp("resetTokenExpiry"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().$onUpdate(() => new Date()).notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});
export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

// ── PERMISSIONS UTILISATEUR ────────────────────────────────────────────────
export const permissionsUtilisateur = pgTable("permissions_utilisateur", {
  id: serial("id").primaryKey(),
  userId: integer("userId").notNull(),
  permission: varchar("permission", { length: 50 }).notNull(),
  autorise: boolean("autorise").default(true).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type PermissionUtilisateur = typeof permissionsUtilisateur.$inferSelect;
export type InsertPermissionUtilisateur = typeof permissionsUtilisateur.$inferInsert;

// ── ARTISANS ───────────────────────────────────────────────────────────────
export const artisans = pgTable("artisans", {
  id: serial("id").primaryKey(),
  userId: integer("userId").notNull().unique(),
  siret: varchar("siret", { length: 14 }),
  nomEntreprise: varchar("nomEntreprise", { length: 255 }),
  adresse: text("adresse"),
  codePostal: varchar("codePostal", { length: 10 }),
  ville: varchar("ville", { length: 100 }),
  telephone: varchar("telephone", { length: 20 }),
  email: varchar("email", { length: 320 }),
  specialite: artisanSpecialiteEnum("specialite").default("plomberie"),
  tauxTVA: numeric("tauxTVA", { precision: 5, scale: 2 }).default("20.00"),
  numeroTVA: varchar("numeroTVA", { length: 20 }),
  iban: varchar("iban", { length: 34 }),
  codeAPE: varchar("codeAPE", { length: 10 }),
  formeJuridique: formeJuridiqueEnum("formeJuridique"),
  capitalSocial: numeric("capitalSocial", { precision: 12, scale: 2 }),
  villeRCS: varchar("villeRCS", { length: 100 }),
  numeroRM: varchar("numeroRM", { length: 50 }),
  logo: text("logo"),
  slug: varchar("slug", { length: 255 }).unique(),
  icalToken: varchar("icalToken", { length: 64 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().$onUpdate(() => new Date()).notNull(),
});
export type Artisan = typeof artisans.$inferSelect;
export type InsertArtisan = typeof artisans.$inferInsert;

// ── CLIENTS ────────────────────────────────────────────────────────────────
export const clients = pgTable("clients", {
  id: serial("id").primaryKey(),
  artisanId: integer("artisanId").notNull(),
  nom: varchar("nom", { length: 255 }).notNull(),
  prenom: varchar("prenom", { length: 255 }),
  email: varchar("email", { length: 320 }),
  telephone: varchar("telephone", { length: 20 }),
  adresse: text("adresse"),
  codePostal: varchar("codePostal", { length: 10 }),
  ville: varchar("ville", { length: 100 }),
  adresseFacturation: text("adresseFacturation"),
  codePostalFacturation: varchar("codePostalFacturation", { length: 10 }),
  villeFacturation: varchar("villeFacturation", { length: 100 }),
  type: clientTypeEnum("type").default("particulier"),
  raisonSociale: varchar("raisonSociale", { length: 255 }),
  siret: varchar("siret", { length: 14 }),
  numeroTVA: varchar("numeroTVA", { length: 20 }),
  etiquettes: varchar("etiquettes", { length: 500 }),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().$onUpdate(() => new Date()).notNull(),
});
export type Client = typeof clients.$inferSelect;
export type InsertClient = typeof clients.$inferInsert;

// ── SESSIONS ───────────────────────────────────────────────────────────────
export const sessions = pgTable("sessions", {
  id: varchar("id", { length: 128 }).primaryKey(),
  userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }),
  expiresAt: bigint("expiresAt", { mode: "number" }).notNull(),
});
export type Session = typeof sessions.$inferSelect;
export type InsertSession = typeof sessions.$inferInsert;

// ── AUDIT LOG ──────────────────────────────────────────────────────────────
export const auditLog = pgTable("audit_log", {
  id: serial("id").primaryKey(),
  artisanId: integer("artisanId").notNull(),
  userId: integer("userId").notNull(),
  entityType: varchar("entityType", { length: 50 }).notNull(),
  entityId: integer("entityId").notNull(),
  action: varchar("action", { length: 50 }).notNull(),
  details: text("details"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type AuditLog = typeof auditLog.$inferSelect;
export type InsertAuditLog = typeof auditLog.$inferInsert;
