DELETE FROM "factures_recurrentes" WHERE "contratId" NOT IN (SELECT id FROM "contrats_maintenance");--> statement-breakpoint
DELETE FROM "interventions_contrat" WHERE "contratId" NOT IN (SELECT id FROM "contrats_maintenance");--> statement-breakpoint
DELETE FROM "interventions_mobile" WHERE "interventionId" NOT IN (SELECT id FROM "interventions");--> statement-breakpoint
DELETE FROM "photos_interventions" WHERE "interventionMobileId" NOT IN (SELECT id FROM "interventions_mobile");--> statement-breakpoint
DELETE FROM "demandes_avis" WHERE "interventionId" NOT IN (SELECT id FROM "interventions");--> statement-breakpoint
ALTER TABLE "factures_recurrentes" ADD CONSTRAINT "factures_recurrentes_contratId_contrats_maintenance_id_fk" FOREIGN KEY ("contratId") REFERENCES "public"."contrats_maintenance"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interventions_contrat" ADD CONSTRAINT "interventions_contrat_contratId_contrats_maintenance_id_fk" FOREIGN KEY ("contratId") REFERENCES "public"."contrats_maintenance"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interventions_mobile" ADD CONSTRAINT "interventions_mobile_interventionId_interventions_id_fk" FOREIGN KEY ("interventionId") REFERENCES "public"."interventions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "photos_interventions" ADD CONSTRAINT "photos_interventions_interventionMobileId_interventions_mobile_id_fk" FOREIGN KEY ("interventionMobileId") REFERENCES "public"."interventions_mobile"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "demandes_avis" ADD CONSTRAINT "demandes_avis_interventionId_interventions_id_fk" FOREIGN KEY ("interventionId") REFERENCES "public"."interventions"("id") ON DELETE cascade ON UPDATE no action;